services:
  pihole:
    container_name: pihole
    image: mpgirro/pihole-unbound:latest
    hostname: drogon
    domainname: example.com
    ports:
      - 443:443/tcp
      - 53:53/tcp
      - 53:53/udp
      - ${PIHOLE_WEBPORT:-80}:80/tcp #Allows use of different port to access pihole web interface when other docker containers use port 80
      - 5335:5335/tcp # Uncomment to enable unbound access on local server
      - 22/tcp # Uncomment to enable SSH
    environment: 
      - .env
    dns:
      - 127.0.0.1 # system resolver       
    volumes:
      - ~/pihole/etc_pihole-unbound:/etc/pihole:rw
      - ~/pihole/etc_pihole_dnsmasq-unbound:/etc/dnsmasq.d:rw
    restart: unless-stopped

volumes:
  etc_pihole-unbound:
  etc_pihole_dnsmasq-unbound: