- hosts: "*"
  become: yes
  become_method: sudo
  tasks:
    - name: update apt list
      apt:
        update_cache: yes
        upgrade: 'yes'
        
    - name: remove old packages and clean cache
    apt:
      autoremove: yes
      autoclean: yes
      clean: yes      
