- hosts: "*"
  become: yes
  tasks:
    - name: apt
      apt:
        update_cache: yes
        upgrade: 'yes'

# ansible-playbook ./playbooks/apt.yml --user romeo --ask-pass --ask-become-pass -i ./inventory/hosts

# ansible-playbook ./playbooks/apt.yml --ask-become-pass -i ./inventory/hosts