- name: Install Docker + Docker‑Compose on Ubuntu
  hosts: *
  become: true 
  gather_facts: true

  vars:
    # If you prefer a fixed user instead of the remote login account,
    # override this variable in your inventory or a host_vars file.
    docker_group_user: "{{ ansible_user }}"

  tasks:
    # -------------------------------------------------------------
    # 1. Prepare the keyring directory and import Docker’s GPG key
    # -------------------------------------------------------------
    - name: Ensure keyrings directory exists
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'
        owner: root
        group: root

    - name: Download Docker GPG key to keyring
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.gpg
        mode: '0644'
        force: true          # re‑download if the file changes
      register: gpg_download

    - name: Verify Docker GPG key file (ensures it is a valid key)
      command: gpg --dearmor -o /dev/null /etc/apt/keyrings/docker.gpg
      args:
        warn: false
      when: gpg_download.changed

    # -------------------------------------------------------------
    # 2. Add Docker's official APT repository
    # -------------------------------------------------------------
    - name: Add Docker APT repo
      apt_repository:
        repo: "deb [arch={{ ansible_architecture }} signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
        filename: docker
      register: docker_repo

    - name: Update apt cache (post‑repo add)
      apt:
        update_cache: yes
      when: docker_repo.changed

    # -------------------------------------------------------------
    # 3. Install Docker Engine, Docker‑Compose (plugin) & related packages
    # -------------------------------------------------------------
    - name: Install Docker & related packages
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
          - docker-compose
        state: present
        update_cache: yes
        install_recommends: false
      register: docker_pkg_install

    # -------------------------------------------------------------
    # 4. Ensure the user belongs to the docker group
    # -------------------------------------------------------------
    - name: Add user to docker group
      user:
        name: "{{ docker_group_user }}"
        groups: docker
        append: yes
      register: docker_group_user_mod
