---
- name: Install Docker + Docker‑Compose on Ubuntu
  hosts: all
  become: true
  gather_facts: true

  vars:
    # If you want another user, override this in inventory or host_vars
    docker_group_user: "Romeo"

  tasks:
    # -------------------------------------------------------------
    # 1. Update apt cache (the very first step in the shell script)
    # -------------------------------------------------------------
    - name: Run apt‑get update
      apt:
        update_cache: yes

    # -------------------------------------------------------------
    # 2. Install prerequisites
    # -------------------------------------------------------------
    - name: Install ca‑certificates, curl and gnupg
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
        state: present

    # -------------------------------------------------------------
    # 3. Prepare keyrings directory and import Docker GPG key
    # -------------------------------------------------------------
    - name: Ensure /etc/apt/keyrings exists
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Download Docker GPG key to keyring
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.gpg
        mode: '0644'
        force: true

    - name: Make the key readable for apt
      file:
        path: /etc/apt/keyrings/docker.gpg
        mode: '0644'

    # -------------------------------------------------------------
    # 4. Add Docker’s official APT repository
    # -------------------------------------------------------------
    - name: Add Docker APT repo
      apt_repository:
        repo: "deb [arch={{ ansible_architecture | replace('x86_64','amd64') }} signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        filename: docker
        state: present
      register: docker_repo

    - name: Update apt cache after adding repo
      apt:
        update_cache: yes
      when: docker_repo.changed

    # -------------------------------------------------------------
    # 5. Install Docker & Compose packages
    # -------------------------------------------------------------
    - name: Install Docker Engine, Compose plugin and related packages
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
          - docker-compose
        state: present
        update_cache: yes
      register: docker_pkg

    # -------------------------------------------------------------
    # 6. Add the user to the docker group
    # -------------------------------------------------------------
    - name: Ensure user is in docker group
      user:
        name: "{{ docker_group_user }}"
        groups: docker
        append: yes
      register: docker_group
