- name: install nano
  hosts: "*"
  tasks:
    - name: install nano
      apt:
        name: nano
        state: present
        update_cache: true
      become: true
      
# ansible-playbook ./playbooks/nano.yml --user romeo --ask-pass --ask-become-pass -i ./inventory/hosts