- name: install latest qemu-guest-agent
  hosts: "*"
  tasks:
    - name: install qemu-guest-agent
      apt:
        name: qemu-guest-agent
        state: present
        update_cache: true
      become: true

# ansible-playbook ./playbooks/qemu.guest-agent.yml --user romeo --ask-pass --ask-become-pass -i ./inventory/hosts