- name: Check if restart is required
  hosts: all
  become: true

  tasks:
    - name: Check if system reboot is required
      become: true
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: reboot_required
      
    - name: check for reboot required
      register: reboot_required_file
      stat: path=/var/run/reboot-required get_md5=no
    
    - name: Report if reboot is required
      ansible.builtin.debug:
        msg: "Reboot is required"
      when: reboot_required.stat.exists
