- name: Check if restart is required
  hosts: all
  become: true

  tasks:
    - name: Check if system reboot is required
      become: true
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: reboot_required

    - name: Report if reboot is required
      ansible.builtin.debug:
        msg: "Reboot is required"
      when: reboot_required.stat.exists
      
      # ansible-playbook ./playbooks/reboot-required.yml --user romeo --ask-pass --ask-become-pass -i ./inventory/hosts

      # ansible-playbook ./playbooks/reboot-required.yml --ask-become-pass -i ./inventory/hosts