
    name: Install SSH on Linux hosts
    hosts: "*"
    become: true

    tasks:

        name: Install OpenSSH package
        apt:
          name: openssh-server
          state: present





 # ansible-playbook ./playbooks/zsh.yml --user romeo --ask-pass --ask-become-pass -i ./inventory/hosts