services:
  collabora:
    image: collabora/code:latest
    container_name: collabora
#    hostname: collabora.example.com
    restart: unless-stopped
    ports:
      - 9980:9980
    environment:
      - TIMEZONE=America/Los_Angeles
      - USERNAME=${COLLABORA_USERNAME}
      - PASSWORD=${COLLABORA_PASSWORD}
      - aliasgroup1=https://subdomain.example.com
#      - server_name=collabora.example.com
      - extra_params=--o:ssl.enable=false --o:ssl.termination=true --o:user_interface.mode=compact --o:net.proto=IPv4 --o:hexify_embedded_urls=true --o:logging.level=warning
      - LOG_TYPE=FILE
    cap_add:
      - MKNOD
      - NET_ADMIN
    networks:
      - proxy
      - services
    volumes:
      - ./logs:/logs
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    privileged: true

networks:
  proxy:
    external: true
  services:
    external: true
