services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: $USER:$USER
    environment:
      - TZ=America/Los_Angeles
    volumes:
      - /path/to/config:/config
      - /path/to/cache:/cache
      - /path/to/NAS/Movies:/Movies:ro
      - /path/to/NAS/TVShows:/TVShows:ro
      - /path/to/NAS/Music:/Music:ro
    ports:
      - 8096:8096
      - 8920:8920 #optional
    devices: 
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card0:/dev/dri/card0
    restart: unless-stopped
    networks:
      proxy:
    security_opt:
      - no-new-privileges:true

networks:
  proxy:
    external: true
